spring.application.name=musai-management

spring.datasource.url=jdbc:mysql://localhost:3306/musai_management?useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

#Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# App Properties
musai.app.jwtSecret= ======================Musai=Spring=Boot===========================
musai.app.jwtExpirationMs=3600000

#frontend url
#frontend.url=http://163.43.229.228:5173
#local
frontend.url=http://localhost:5173

#path save file
#upload.dir=/home/ubuntu/projects/musai-management/uploads/
#local
upload.dir=C:/Users/owner/pro/uploads/

# SMTP設定
spring.mail.host=smtp.sakura.ne.jp
#spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chamith@musai-jin.com
spring.mail.password=janipama94
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# アプリ固有設定
#app.admin.email=yj-an@musai-jin.com
app.admin.email=chamith19dj@gmail.com
app.mail.from=chamith@musai-jin.com
app.mail.from.name=Leave System
